from flask import Flask, render_template, redirect
from flask import url_for
from engine.ui_components import get_header_section, get_features_section


app = Flask(__name__)
app.secret_key = "secret123"


@app.route("/")
def landing():
    # 🔥 DYNAMIC DATA (injected by Developer Agent later)
    product_name = "Test Startup"
    product_tagline = "Testing pipeline"

    # <AUTO-GENERATED-MODULES>
    modules = []
    # </AUTO-GENERATED-MODULES>

    return render_template(
        "index.html",
        # BASIC INFO
        product_name=product_name,
        product_tagline=product_tagline,
        # 🔥 GENERATED UI
        header_section=get_header_section(product_name, product_tagline),
        features_section=get_features_section(modules),
    )


@app.route("/dashboard")
def dashboard():
    return render_template("dashboard.html", product_name="Test Startup")


@app.route("/logout")
def logout():
    return redirect("/")


if __name__ == "__main__":
    import sys

    port = int(sys.argv[1]) if len(sys.argv) > 1 else 5000

    app.run(host="0.0.0.0", port=port, debug=True)
