from flask import Flask, render_template, redirect
from flask import url_for
from engine.ui_components import (
    get_header_section,
    get_features_section,
    get_module_page_section,
)


app = Flask(__name__)
app.secret_key = "secret123"
# <AUTO-GENERATED-MODULES>
GLOBAL_MODULES = [
    {
        "name": "Pipeline Management",
        "description": "Manages testing pipeline workflow",
        "features": ["Pipeline creation", "Test case management", "Execution control"],
    },
    {
        "name": "Test Automation",
        "description": "Automates testing process",
        "features": [
            "API integration",
            "Test script management",
            "Test result analysis",
        ],
    },
    {
        "name": "Reporting and Analytics",
        "description": "Provides insights on testing performance",
        "features": [
            "Test result visualization",
            "Performance metrics calculation",
            "Alert system",
        ],
    },
    {
        "name": "User Management",
        "description": "Manages user access and permissions",
        "features": [
            "User registration",
            "Role-based access control",
            "User authentication",
        ],
    },
]
# </AUTO-GENERATED-MODULES>


def slugify(name):
    return str(name).lower().replace(" ", "_")


@app.route("/")
def landing():
    product_name = "{{ product_name }}"
    product_tagline = "{{ product_tagline }}"

    return render_template(
        "index.html",
        product_name=product_name,
        product_tagline=product_tagline,
        header_section=get_header_section(product_name, product_tagline),
        features_section=get_features_section(GLOBAL_MODULES),
    )


@app.route("/module/<module_name>")
def module_page(module_name):
    module_data = next(
        (m for m in GLOBAL_MODULES if slugify(m["name"]) == module_name),
        None,
    )

    if not module_data:
        return {"error": "Module not found"}, 404

    return render_template(
        "module_page.html",
        module_ui=get_module_page_section(module_data),
    )


@app.route("/dashboard")
def dashboard():
    return render_template("dashboard.html", product_name="Test Startup")


@app.route("/logout")
def logout():
    return redirect("/")


if __name__ == "__main__":
    import sys

    port = int(sys.argv[1]) if len(sys.argv) > 1 else 5000

    app.run(host="0.0.0.0", port=port, debug=True)
